=== StanislavPopkov/test-task-xml/src/main/resources/xml/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://parsetest.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://parsetest.ru"
           attributeFormDefault="unqualified" elementFormDefault="qualified">

    <xs:element name="order">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="services"/>
            <xs:element type="xs:string" name="summa"/>
        </xs:sequence>
    </xs:complexType>
    </xs:element>

    <xs:element name="services">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="serv"/>
        </xs:sequence>
    </xs:complexType>
    </xs:element>

    <xs:element name="serv">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="serv_id" type="xs:string"/>
            <xs:element name="bic" type="xs:long"/>
            <xs:element type="xs:string" name="schet"/>
            <xs:element type="xs:string" name="corr_schet"/>
            <xs:element ref="pars">
            </xs:element>
            <xs:element type="xs:string" name="sys_message"/>
        </xs:sequence>
        <xs:attribute type="xs:boolean" name="isClosed" use="required"/>
    </xs:complexType>
    </xs:element>

    <xs:element name="pars">
    <xs:complexType>
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element ref="par"/>
        </xs:sequence>
    </xs:complexType>
    </xs:element>

    <xs:element name="par">
    <xs:complexType mixed="true">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element ref="par_list" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="step" use="optional"/>
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="fullname" use="optional"/>
        <xs:attribute type="xs:string" name="comment" use="optional"/>
        <xs:attribute type="xs:string" name="isEditable" use="optional"/>
        <xs:attribute type="xs:string" name="isScanable" use="optional"/>
        <xs:attribute type="xs:string" name="isVisible" use="optional"/>
        <xs:attribute type="xs:string" name="isRequired" use="optional"/>
        <xs:attribute type="xs:string" name="isPrinted" use="optional"/>
        <xs:attribute type="xs:string" name="isValidateOnLine" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
        <xs:attribute type="xs:string" name="min_length" use="optional"/>
        <xs:attribute type="xs:string" name="max_length" use="optional"/>
        <xs:attribute type="xs:string" name="double_input" use="optional"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
        <xs:attribute type="xs:string" name="reg_exp" use="optional"/>
        <xs:attribute type="xs:string" name="from_debt" use="optional"/>
    </xs:complexType>
    </xs:element>

    <xs:element name="par_list">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="value" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    </xs:element>


</xs:schema>

=== StanislavPopkov/test-task-xml/src/main/resources/data.xml
<order xmlns="http://parsetest.ru"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://parsetest.ru data.xsd">
    <services>
        <serv isClosed="0">
        <serv_id>*****</serv_id>
        <bic>05009991</bic>
        <schet>т</schet>
        <corr_schet></corr_schet>
        <pars>
            <par step="1" name="ФИОПЛАТЕЛЬЩИКА" fullname="ФИОплательщика" comment="ВведитеФИОполностью, лицазакогооплачиваетсяуслуга, например: ИвановИванИванович" isEditable="1" isScanable="0" isVisible="1" isRequired="1" isPrinted="1" isValidateOnLine="0" type="T" min_length="0" max_length="50" double_input="0" value="Лыулао" reg_exp="^[А-яЁё  -]*[А-яЁё]{1,}[А-яЁё]{1,}[А-яЁё  -]*$" from_debt="0"/>
            <par step="1" name="АДРЕС_ПЛАТЕЛЬЩИКА" fullname="Адрес получателя услуги" comment="Введите адрес лица за кого оплачивается услуга, например: г. Москва, ул. Шверникад.11-111" isEditable="1" isScanable="0" isVisible="1" isRequired="1" isPrinted="1" isValidateOnLine="0" type="T" min_length="1" max_length="150" double_input="0" value="ыуавуы" reg_exp="^[А-яЁё0-9.,  /-]{5,}$" from_debt="0"/>
            <par step="1" name="ВИД_ДОК" fullname="Виддокумента" comment="Выберитевиддокумента, лицазакогооплачиваетсяуслуга" isEditable="1" isScanable="0" isVisible="1" isRequired="1" isPrinted="1" isValidateOnLine="0" type="M" min_length="0" max_length="250" double_input="0" value="ПАСПОРТРФ" reg_exp="" from_debt="0">
                <par_list value="ПАСПОРТРФ"/>
                <par_list value="СВИД О РОЖДЕНИИ"/>
                <par_list value="ИНН"/>
                <par_list value="ВОДИТУДОСТОВЕРЕНИЕ"/>
                <par_list value="СВИД_РЕГ_ТС"/>
                <par_list value="ПАСПОРТМОРЯКА"/>
                <par_list value="УДОСТОВЕРВОЕНСЛУЖ"/>
                <par_list value="ОХОТНИЧИЙБИЛЕТ"/>
                <par_list value="РАЗРЕШ НА ОРУЖИЕ"/>
            </par>
            <par step="1" name="НОМЕР ДОКУМЕНТА" fullname="Серия и номер документа" comment="Введите серию и номер документа, лица за кого оплачивается услуга" isEditable="1" isScanable="0" isVisible="1" isRequired="1" isPrinted="1" isValidateOnLine="0" type="C" min_length="10" max_length="10" double_input="0" value="1234556778" reg_exp="" from_debt="0"/>
            <par step="1" name="ГРАЖДАНСТВО" fullname="Гражданство" comment="Выберите гражданство, лица за кого оплачивается услуга, из списка" isEditable="1" isScanable="0" isVisible="1" isRequired="1" isPrinted="1" isValidateOnLine="1" type="M" min_length="0" max_length="250" double_input="0" value="РОССИЯ" reg_exp="" from_debt="0">
            <par_list value="РОССИЯ"/>
        </par>
    </pars>
    <sys_message></sys_message>
</serv>
        </services>
<summa>0</summa>
        </order>
